#include <gtest/gtest.h>
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>
#include "base/alloc.h"
#include "model/qwen2.h"
#include "serving/scheduler.h"
namespace {
template<class T>std::vector<T>Read(const std::string&p){std::ifstream f(p,std::ios::binary);f.seekg(0,std::ios::end);auto n=f.tellg();f.seekg(0);std::vector<T>v(n/sizeof(T));f.read(reinterpret_cast<char*>(v.data()),n);return v;}
TEST(Qwen25VLChunkedTest, FourFixturesCrossMediaSpansAtTwoChunkCaps){const char*mp=std::getenv("PBE_QWEN25_VL_MODEL"),*tp=std::getenv("PBE_QWEN25_VL_TOKENIZER"),*fd=std::getenv("PBE_QWEN25_VL_FIXTURE_DIR");if(!mp||!tp||!fd)GTEST_SKIP()<<"set Qwen25 VL env";model::Qwen2Model model(base::TokenizerType::kEncodeBpe,tp,mp,false);model.set_kv_cache_blocks_per_layer(256);model.set_serving_workspace_token_capacity(256);model.set_radix_cache_enabled(false);ASSERT_TRUE(model.init(base::DeviceType::kDeviceCUDA,0));auto alloc=base::CUDADeviceAllocatorFactory::get_instance();for(const std::string name:{"text","one_image_224","one_image_wide","two_images"})for(int cap:{17,31}){auto ids=Read<int32_t>(std::string(fd)+"/"+name+".input_ids.i32.bin");auto pos=Read<int32_t>(std::string(fd)+"/"+name+".position_ids.i32.bin");auto emb=Read<uint16_t>(std::string(fd)+"/"+name+".inputs_embeds.bf16.bin");auto expected=Read<float>(std::string(fd)+"/"+name+".last_logits.f32.bin");ASSERT_EQ(pos.size(),ids.size()*3);serving::SchedulerConfig cfg;cfg.max_num_seqs=1;cfg.max_num_batched_tokens=cap;cfg.prefill_chunk_cap=cap;serving::Scheduler sched(cfg,model.kv_cache_manager());sched.add_request(ids,serving::GenerationConfig(1));bool checked=false;while(sched.has_active_requests()){auto out=sched.schedule_step();ASSERT_EQ(out.scheduled_seqs.size(),1u);int start=out.scheduled_seqs[0]->computed_tokens,n=out.total_tokens;tensor::Tensor eg(base::DataType::kDataTypeBf16,n,2048,true,alloc),pg(base::DataType::kDataTypeInt32,3,n,true,alloc);alloc->memcpy(emb.data()+size_t(start)*2048,eg.ptr<uint16_t>(),eg.byte_size(),base::MemcpyKind::kMemcpyCPU2CUDA,nullptr,true);std::vector<int32_t>chunk_pos;for(int axis=0;axis<3;++axis)chunk_pos.insert(chunk_pos.end(),pos.begin()+axis*ids.size()+start,pos.begin()+axis*ids.size()+start+n);alloc->memcpy(chunk_pos.data(),pg.ptr<int32_t>(),pg.byte_size(),base::MemcpyKind::kMemcpyCPU2CUDA,nullptr,true);auto batch=sched.build_mixed_batch(out,model.device_context()->compute_queue);batch.input_embeddings_override=eg;batch.mrope_positions=pg;auto status=model.forward_mixed_batch(batch);ASSERT_TRUE(status)<<name<<" cap="<<cap;if(start+n==ids.size()){std::vector<float>actual;ASSERT_TRUE(model.copy_logits_row_to_host(n-1,&actual));double mx=0,mean=0;for(size_t i=0;i<actual.size();++i){double e=std::abs(actual[i]-expected[i]);mx=std::max(mx,e);mean+=e;}mean/=actual.size();EXPECT_LT(mx,1.0)<<name<<" cap="<<cap;EXPECT_LT(mean,.13)<<name<<" cap="<<cap;checked=true;}auto sampled=model.batch_sample(batch,out);sched.process_outputs(out,batch,sampled,[&](int token){return model.is_sentence_ending(token);});}EXPECT_TRUE(checked);std::cout<<"QWEN25_CHUNKED case="<<name<<" cap="<<cap<<" passed=1\n";}}
}
