#include "serving/request_coordinator.h"
namespace serving {
bool RequestCoordinator::submit(uint64_t id,uint64_t generation,std::vector<MultimodalRequestPart>parts,std::chrono::steady_clock::time_point deadline){if(!id||!generation||parts.empty()||deadline<=std::chrono::steady_clock::now()||requests_.count(id))return false;requests_.emplace(id,CoordinatedRequest{id,generation,RequestStage::kEncode,deadline,std::move(parts),{}});return true;}
bool RequestCoordinator::complete(uint64_t id,uint64_t generation,RequestStage stage){auto it=requests_.find(id);if(it==requests_.end()||it->second.generation!=generation||it->second.stage!=stage)return false;switch(stage){case RequestStage::kEncode:it->second.stage=RequestStage::kJoin;break;case RequestStage::kJoin:it->second.stage=RequestStage::kPrefill;break;case RequestStage::kPrefill:it->second.stage=RequestStage::kDecode;break;case RequestStage::kDecode:it->second.stage=RequestStage::kFinished;break;default:return false;}return true;}
bool RequestCoordinator::fail(uint64_t id,uint64_t generation,std::string error){auto it=requests_.find(id);if(it==requests_.end()||it->second.generation!=generation||error.empty())return false;if(it->second.stage>=RequestStage::kFinished)return false;it->second.stage=RequestStage::kFailed;it->second.error=std::move(error);return true;}
bool RequestCoordinator::cancel(uint64_t id,uint64_t generation){auto it=requests_.find(id);if(it==requests_.end()||it->second.generation!=generation||it->second.stage>=RequestStage::kFinished)return false;it->second.stage=RequestStage::kCancelled;it->second.error="cancelled";return true;}
void RequestCoordinator::expire(std::chrono::steady_clock::time_point now){for(auto&x:requests_)if(x.second.stage<RequestStage::kFinished&&x.second.deadline<=now){x.second.stage=RequestStage::kFailed;x.second.error="deadline_exceeded";}}
const CoordinatedRequest*RequestCoordinator::get(uint64_t id)const{auto it=requests_.find(id);return it==requests_.end()?nullptr:&it->second;}
}  // namespace serving
