#include <cstdlib>
#include <chrono>
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
#include <string>
#include <stdexcept>
#include <unistd.h>

#include "data/data_client.h"
#include "data/node_agent.h"

namespace {
uint64_t ParseU64(const char* s) { char* end=nullptr;unsigned long long v=std::strtoull(s,&end,10);if(!end||*end)throw std::invalid_argument(s);return v; }
std::string Hex(const data::Digest256& d){static const char x[]="0123456789abcdef";std::string s;for(auto b:d){s.push_back(x[b>>4]);s.push_back(x[b&15]);}return s;}
bool FromHex(const std::string&s,data::Digest256*d){if(s.size()!=64)return false;for(size_t i=0;i<32;++i){auto cv=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;};int a=cv(s[2*i]),b=cv(s[2*i+1]);if(a<0||b<0)return false;(*d)[i]=(a<<4)|b;}return true;}
void Usage(){std::cerr<<"usage:\n  pbe_data_service serve ENDPOINT CAPACITY_BYTES [OBJECTS]\n  pbe_data_service serve-gpu ENDPOINT CAPACITY_BYTES DEVICE LAYERS BLOCKS BLOCK_SIZE KV_HEADS HEAD_SIZE DTYPE [OBJECTS]\n  pbe_data_service serve-gpu-weights ENDPOINT CAPACITY_BYTES DEVICE LAYERS BLOCKS BLOCK_SIZE KV_HEADS HEAD_SIZE DTYPE MODEL_FILE MODEL_SHA256 LAYOUT_ID [STAGING_BYTES] [OBJECTS]\n  pbe_data_service put ENDPOINT FILE REPRESENTATION\n  pbe_data_service get ENDPOINT CONTENT_HEX REPRESENTATION OUTPUT\n  pbe_data_service stats|ipc-stats|weight-stats ENDPOINT\n  pbe_data_service acquire-weight ENDPOINT MODEL_SHA256 LAYOUT_ID DTYPE BYTES OP_OWNER OP_SEQUENCE\n  pbe_data_service release-ipc|release-weight ENDPOINT SERVICE_INCARNATION CONSUMER_INCARNATION LEASE_ID\n  pbe_data_service shutdown ENDPOINT\n";}
}
int main(int argc,char**argv){
  try{
    if(argc<3){Usage();return 2;}std::string command=argv[1],endpoint=argv[2];
    if(command=="serve") {if(argc<4){Usage();return 2;}data::NodeAgentConfig c;c.endpoint=endpoint;c.capacity_bytes=ParseU64(argv[3]);if(argc>4)c.capacity_objects=ParseU64(argv[4]);data::NodeAgent a(c);return a.run();}
    if(command=="serve-gpu") {if(argc<11){Usage();return 2;}data::NodeAgentConfig c;c.endpoint=endpoint;c.capacity_bytes=ParseU64(argv[3]);c.ipc_pool_device=static_cast<int32_t>(ParseU64(argv[4]));c.ipc_pool_num_layers=ParseU64(argv[5]);c.ipc_pool_num_blocks=ParseU64(argv[6]);c.ipc_pool_block_size=ParseU64(argv[7]);c.ipc_pool_num_kv_heads=ParseU64(argv[8]);c.ipc_pool_head_size=ParseU64(argv[9]);c.ipc_pool_storage_dtype=ParseU64(argv[10]);const uint64_t type_bytes=c.ipc_pool_storage_dtype==4?2:(c.ipc_pool_storage_dtype==1?4:0);if(!type_bytes)return 2;c.ipc_pool_bytes=static_cast<uint64_t>(c.ipc_pool_num_layers)*2*c.ipc_pool_num_blocks*c.ipc_pool_block_size*c.ipc_pool_num_kv_heads*c.ipc_pool_head_size*type_bytes;if(argc>11)c.capacity_objects=ParseU64(argv[11]);data::NodeAgent a(c);return a.run();}
    if(command=="serve-gpu-weights") {if(argc<14||argc>16||std::string(argv[13])!=data::kQwen2Bf16SharedWeightLayout){Usage();return 2;}data::NodeAgentConfig c;c.endpoint=endpoint;c.capacity_bytes=ParseU64(argv[3]);c.ipc_pool_device=static_cast<int32_t>(ParseU64(argv[4]));c.ipc_pool_num_layers=ParseU64(argv[5]);c.ipc_pool_num_blocks=ParseU64(argv[6]);c.ipc_pool_block_size=ParseU64(argv[7]);c.ipc_pool_num_kv_heads=ParseU64(argv[8]);c.ipc_pool_head_size=ParseU64(argv[9]);c.ipc_pool_storage_dtype=ParseU64(argv[10]);const uint64_t type_bytes=c.ipc_pool_storage_dtype==4?2:(c.ipc_pool_storage_dtype==1?4:0);if(!type_bytes)return 2;c.ipc_pool_bytes=static_cast<uint64_t>(c.ipc_pool_num_layers)*2*c.ipc_pool_num_blocks*c.ipc_pool_block_size*c.ipc_pool_num_kv_heads*c.ipc_pool_head_size*type_bytes;c.shared_weight_path=argv[11];if(!FromHex(argv[12],&c.shared_weight_content))return 2;c.shared_weight_layout=data::DataChecksum(reinterpret_cast<const uint8_t*>(argv[13]),std::strlen(argv[13]));c.shared_weight_dtype=static_cast<base::DataType>(c.ipc_pool_storage_dtype);if(argc>14)c.shared_weight_staging_bytes=ParseU64(argv[14]);if(argc>15)c.capacity_objects=ParseU64(argv[15]);data::NodeAgent a(c);return a.run();}
    data::DataClient client(endpoint);
    if(command=="put") {if(argc!=5){Usage();return 2;}std::ifstream f(argv[3],std::ios::binary);std::vector<uint8_t>b((std::istreambuf_iterator<char>(f)),{});if(!f&&b.empty()){std::cerr<<"cannot read input\n";return 3;}uint64_t owner=0;auto s=client.ping(&owner);if(s!=data::DataError::kOk)return static_cast<int>(s);data::DataReservation r;r.operation={owner,(static_cast<uint64_t>(::getpid())<<32)^static_cast<uint64_t>(std::chrono::steady_clock::now().time_since_epoch().count())};r.kind=data::DataKind::kKVPage;r.content=data::ContentIdFromBytes(b.data(),b.size());r.representation=data::RepresentationIdFromString(argv[4]);r.logical_bytes=b.size();data::AllocationHandle h;s=client.reserve(r,&h);if(s!=data::DataError::kOk)return static_cast<int>(s);data::DataRef ref;s=client.seal(h,b,data::DataChecksum(b.data(),b.size()),&ref);if(s!=data::DataError::kOk)return static_cast<int>(s);std::cout<<"PBE_DATA_PUT pid="<<::getpid()<<" content="<<Hex(ref.content.digest)<<" allocation="<<ref.allocation.allocation_id<<" bytes="<<b.size()<<" transport=host_copy\n";return 0;}
    if(command=="get") {if(argc!=6){Usage();return 2;}data::ContentId c;if(!FromHex(argv[3],&c.digest))return 2;data::RemoteDataLease lease;auto s=client.acquire(data::DataKind::kKVPage,c,data::RepresentationIdFromString(argv[4]),data::DataLeaseKind::kCompute,&lease);if(s!=data::DataError::kOk)return static_cast<int>(s);std::ofstream f(argv[5],std::ios::binary);f.write(reinterpret_cast<const char*>(lease.bytes.data()),lease.bytes.size());if(!f)return 3;s=client.release(lease.token);if(s!=data::DataError::kOk)return static_cast<int>(s);std::cout<<"PBE_DATA_GET pid="<<::getpid()<<" lease="<<lease.token.lease_id<<" bytes="<<lease.bytes.size()<<" transport=host_copy\n";return 0;}
    if(command=="stats") {data::DataServiceStats s;auto e=client.stats(&s);if(e!=data::DataError::kOk)return static_cast<int>(e);std::cout<<"incarnation="<<s.owner_incarnation<<" bytes_used="<<s.bytes_used<<" objects="<<s.object_count<<" leases="<<s.active_leases<<" bytes_received="<<s.bytes_received<<" bytes_sent="<<s.bytes_sent<<" requests="<<s.requests<<"\n";return 0;}
    if(command=="ipc-stats") {data::IpcPoolStats s;auto e=client.ipc_pool_stats(&s);if(e!=data::DataError::kOk)return static_cast<int>(e);std::cout<<"total_slots="<<s.total_slots<<" free_slots="<<s.free_slots<<" active_grants="<<s.active_grants<<"\n";return 0;}
    if(command=="weight-stats") {data::SharedWeightStats s;auto e=client.shared_weight_stats(&s);if(e!=data::DataError::kOk)return static_cast<int>(e);std::cout<<"state="<<static_cast<int>(s.state)<<" owner_incarnation="<<s.owner_incarnation<<" allocation_id="<<s.allocation_id<<" generation="<<s.generation<<" physical_bytes="<<s.physical_bytes<<" upload_bytes="<<s.upload_bytes<<" upload_count="<<s.upload_count<<" active_leases="<<s.active_leases<<" allocation_count="<<s.allocation_count<<" staging_peak_bytes="<<s.staging_peak_bytes<<" upload_ms="<<s.upload_ms<<"\n";return 0;}
    if(command=="acquire-weight") {if(argc!=9)return 2;data::Digest256 content{};if(!FromHex(argv[3],&content)||std::string(argv[4])!=data::kQwen2Bf16SharedWeightLayout)return 2;const auto layout=data::DataChecksum(reinterpret_cast<const uint8_t*>(argv[4]),std::strlen(argv[4]));data::SharedWeightLease lease;const auto e=client.acquire_shared_weight(content,layout,static_cast<base::DataType>(ParseU64(argv[5])),ParseU64(argv[6]),&lease,{ParseU64(argv[7]),ParseU64(argv[8])});if(e!=data::DataError::kOk){std::cerr<<"error="<<static_cast<int>(e)<<"\n";return static_cast<int>(e);}std::cout<<"service_incarnation="<<lease.token.service_incarnation<<" consumer_incarnation="<<lease.token.consumer_incarnation<<" lease_id="<<lease.token.lease_id<<" allocation_id="<<lease.descriptor.allocation_id<<" generation="<<lease.descriptor.generation<<"\n";return 0;}
    if(command=="map-weight") {if(argc!=8)return 2;data::Digest256 content{};if(!FromHex(argv[3],&content)||std::string(argv[4])!=data::kQwen2Bf16SharedWeightLayout)return 2;const auto layout=data::DataChecksum(reinterpret_cast<const uint8_t*>(argv[4]),std::strlen(argv[4]));data::SharedWeightLease lease;auto e=client.acquire_shared_weight(content,layout,static_cast<base::DataType>(ParseU64(argv[5])),ParseU64(argv[6]),&lease);if(e!=data::DataError::kOk)return static_cast<int>(e);data::SharedWeightImport mapping;std::string error;if(!mapping.open(lease.descriptor,static_cast<int32_t>(ParseU64(argv[7])),&error)||!mapping.wait_ready(nullptr,&error)){client.release_shared_weight(lease.token);std::cerr<<error<<"\n";return 3;}client.release_shared_weight(lease.token);std::cout<<"mapped=1 allocation_id="<<lease.descriptor.allocation_id<<" generation="<<lease.descriptor.generation<<"\n";return 0;}
    if(command=="release-ipc") {if(argc!=6)return 2;data::LeaseToken token{ParseU64(argv[3]),ParseU64(argv[4]),ParseU64(argv[5])};return static_cast<int>(client.release_ipc_slots(token));}
    if(command=="release-weight") {if(argc!=6)return 2;data::LeaseToken token{ParseU64(argv[3]),ParseU64(argv[4]),ParseU64(argv[5])};return static_cast<int>(client.release_shared_weight(token));}
    if(command=="shutdown")return static_cast<int>(client.shutdown());
  }catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 2;}Usage();return 2;
}
