#include <cuda_runtime_api.h>

#include <algorithm>
#include <chrono>
#include <climits>
#include <cstring>
#include <iostream>
#include <memory>
#include <string>
#include <unistd.h>
#include <vector>

#include "base/alloc.h"
#include "data/data_client.h"
#include "data/kv_snapshot_codec.h"
#include "data/tensor_bundle.h"
#include "data/wire_io.h"
#include "model/qwen2.h"
#include "serving/scheduler.h"

namespace {
constexpr uint32_t kHostKVPayloadMagic=0x4d564250;
constexpr uint32_t kExternalKVPayloadMagic=0x584b4250;

std::string Hex(const data::Digest256& d){static const char x[]="0123456789abcdef";std::string s;for(auto b:d){s+=x[b>>4];s+=x[b&15];}return s;}
bool Hex(const std::string& s,data::Digest256* d){if(s.size()!=64)return false;auto c=[](char x){if(x>='0'&&x<='9')return x-'0';if(x>='a'&&x<='f')return x-'a'+10;if(x>='A'&&x<='F')return x-'A'+10;return -1;};for(int i=0;i<32;++i){int a=c(s[2*i]),b=c(s[2*i+1]);if(a<0||b<0)return false;(*d)[i]=(a<<4)|b;}return true;}
const data::TensorComponent* Find(const data::TensorBundleSchema& schema,const std::string& name){for(const auto& component:schema.components)if(component.name==name)return &component;return nullptr;}
template<class T>bool ReadComponent(const std::vector<uint8_t>& bytes,const data::TensorComponent* component,std::vector<T>* out){if(!component||component->byte_length%sizeof(T)||component->byte_offset>bytes.size()||component->byte_length>bytes.size()-component->byte_offset)return false;out->resize(component->byte_length/sizeof(T));std::memcpy(out->data(),bytes.data()+component->byte_offset,component->byte_length);return true;}

std::vector<uint8_t> PackHost(const base::KVRequestSnapshot& snapshot,int seed,int64_t delta,const std::vector<int32_t>& prompt){std::vector<uint8_t> kv,out;data::EncodeKVSnapshot(snapshot,&kv);data::wire::Put(kHostKVPayloadMagic,&out);data::wire::Put<uint16_t>(2,&out);data::wire::Put<uint16_t>(0,&out);data::wire::Put<uint32_t>(seed,&out);uint64_t bits=0;std::memcpy(&bits,&delta,8);data::wire::Put(bits,&out);data::wire::Put<uint64_t>(kv.size(),&out);data::wire::Put<uint64_t>(prompt.size(),&out);data::wire::PutBytes(kv.data(),kv.size(),&out);data::wire::PutBytes(prompt.data(),prompt.size()*sizeof(int32_t),&out);return out;}
bool UnpackHost(const std::vector<uint8_t>& bytes,base::KVRequestSnapshot* snapshot,int* seed,int64_t* delta,std::vector<int32_t>* prompt){const uint8_t*p=bytes.data();const uint8_t*e=p+bytes.size();uint32_t magic=0,seed_bits=0;uint16_t version=0,reserved=0;uint64_t delta_bits=0,kv_size=0,prompt_size=0;if(!data::wire::Get(&p,e,&magic)||!data::wire::Get(&p,e,&version)||!data::wire::Get(&p,e,&reserved)||!data::wire::Get(&p,e,&seed_bits)||!data::wire::Get(&p,e,&delta_bits)||!data::wire::Get(&p,e,&kv_size)||!data::wire::Get(&p,e,&prompt_size)||magic!=kHostKVPayloadMagic||version!=2||reserved||kv_size>static_cast<uint64_t>(e-p)||prompt_size>(static_cast<uint64_t>(e-p)-kv_size)/sizeof(int32_t)||kv_size+prompt_size*sizeof(int32_t)!=static_cast<uint64_t>(e-p))return false;*seed=static_cast<int>(seed_bits);std::memcpy(delta,&delta_bits,8);if(data::DecodeKVSnapshot(p,kv_size,1ULL<<30,snapshot)!=data::DataError::kOk)return false;p+=kv_size;prompt->resize(prompt_size);std::memcpy(prompt->data(),p,prompt_size*sizeof(int32_t));return true;}

std::vector<uint8_t> PackExternal(const base::ExternalKVRequestState& state,const data::LeaseToken& pool_lease,int seed,int64_t delta,const std::vector<int32_t>& prompt){std::vector<uint8_t> out;data::wire::Put(kExternalKVPayloadMagic,&out);data::wire::Put<uint16_t>(2,&out);data::wire::Put<uint16_t>(0,&out);data::wire::Put(pool_lease.service_incarnation,&out);data::wire::Put(pool_lease.consumer_incarnation,&out);data::wire::Put(pool_lease.lease_id,&out);data::wire::Put<uint32_t>(seed,&out);uint64_t bits=0;std::memcpy(&bits,&delta,8);data::wire::Put(bits,&out);data::wire::Put<uint32_t>(state.block_size,&out);data::wire::Put<uint32_t>(state.num_layers,&out);data::wire::Put<uint32_t>(state.valid_tokens,&out);data::wire::Put<uint32_t>(state.committed_tokens,&out);data::wire::Put<uint64_t>(prompt.size(),&out);for(const auto& ids:state.block_ids_per_layer){data::wire::Put<uint32_t>(ids.size(),&out);for(int32_t id:ids)data::wire::Put<uint32_t>(id,&out);}data::wire::PutBytes(prompt.data(),prompt.size()*sizeof(int32_t),&out);return out;}
bool UnpackExternal(const std::vector<uint8_t>& bytes,base::ExternalKVRequestState* state,data::LeaseToken* pool_lease,int* seed,int64_t* delta,std::vector<int32_t>* prompt){const uint8_t*p=bytes.data();const uint8_t*e=p+bytes.size();uint32_t magic=0,seed_bits=0,block=0,layers=0,valid=0,committed=0;uint16_t version=0,reserved=0;uint64_t delta_bits=0,prompt_size=0;if(!data::wire::Get(&p,e,&magic)||!data::wire::Get(&p,e,&version)||!data::wire::Get(&p,e,&reserved)||!data::wire::Get(&p,e,&pool_lease->service_incarnation)||!data::wire::Get(&p,e,&pool_lease->consumer_incarnation)||!data::wire::Get(&p,e,&pool_lease->lease_id)||!data::wire::Get(&p,e,&seed_bits)||!data::wire::Get(&p,e,&delta_bits)||!data::wire::Get(&p,e,&block)||!data::wire::Get(&p,e,&layers)||!data::wire::Get(&p,e,&valid)||!data::wire::Get(&p,e,&committed)||!data::wire::Get(&p,e,&prompt_size)||magic!=kExternalKVPayloadMagic||version!=2||reserved||layers==0||layers>256||!pool_lease->lease_id)return false;state->schema_version=1;state->block_size=block;state->num_layers=layers;state->valid_tokens=valid;state->committed_tokens=committed;state->block_ids_per_layer.resize(layers);for(auto& ids:state->block_ids_per_layer){uint32_t count=0;if(!data::wire::Get(&p,e,&count)||count>65536)return false;ids.resize(count);for(auto& id:ids){uint32_t raw=0;if(!data::wire::Get(&p,e,&raw)||raw>INT32_MAX)return false;id=raw;}}if(prompt_size>static_cast<uint64_t>(e-p)/sizeof(int32_t)||prompt_size*sizeof(int32_t)!=static_cast<uint64_t>(e-p))return false;prompt->resize(prompt_size);std::memcpy(prompt->data(),p,prompt_size*sizeof(int32_t));*seed=seed_bits;std::memcpy(delta,&delta_bits,8);return true;}

base::ExternalKVPoolBinding Binding(const data::IpcPoolDescriptor& d,const std::shared_ptr<data::CudaIpcPoolImport>& ipc,const std::vector<int32_t>& initial,const std::vector<int32_t>& granted){base::ExternalKVPoolBinding b;b.base=ipc->mapped();b.bytes=d.bytes;b.device=ipc->device();b.num_layers=d.num_layers;b.num_blocks=d.num_blocks;b.block_size=d.block_size;b.num_kv_heads=d.num_kv_heads;b.head_size=d.head_size;b.storage_dtype=static_cast<base::DataType>(d.storage_dtype);b.initial_blocks=initial;for(int32_t id:granted)if(std::find(initial.begin(),initial.end(),id)==initial.end())b.allocatable_blocks.push_back(id);b.capsule=ipc;return b;}
std::vector<int32_t> CommonBlocks(const base::ExternalKVRequestState& state){if(state.block_ids_per_layer.empty())return {};const auto ids=state.block_ids_per_layer.front();for(const auto& layer:state.block_ids_per_layer)if(layer!=ids)throw std::runtime_error("external pool layer slot IDs diverged");return ids;}

std::vector<int> GenerateRequest(model::Qwen2Model& model,base::RequestId id,int seed,int64_t delta,int steps,const std::vector<int32_t>& prompt){serving::SchedulerConfig cfg;cfg.max_num_seqs=1;cfg.max_num_batched_tokens=16;serving::Scheduler scheduler(cfg,model.kv_cache_manager());serving::GenerationConfig generation(steps);generation.sampling.repetition_penalty=1.05;const int32_t initial_context=model.kv_cache_manager()->get_context_len(id);scheduler.add_decode_ready_request(id,prompt,generation,initial_context,seed);size_t produced=1;auto allocator=base::CUDADeviceAllocatorFactory::get_instance();while(scheduler.has_active_requests()){auto output=scheduler.schedule_step();auto batch=scheduler.build_decode_batch(output,model.device_context()->compute_queue);int32_t position=initial_context+delta+static_cast<int32_t>(produced)-1;allocator->memcpy(&position,batch.positions.ptr<int32_t>(),sizeof(position),base::MemcpyKind::kMemcpyCPU2CUDA,model.device_context()->compute_queue,false);auto status=model.forward_decode_batch(batch);if(!status)throw std::runtime_error(status.get_err_msg());auto sampled=model.batch_sample(batch,output);produced+=sampled.size();scheduler.process_outputs(output,batch,sampled,[](int32_t){return false;});}auto finished=scheduler.pop_finished();if(finished.size()!=1)throw std::runtime_error("decode did not finish");return finished[0].output_tokens;}
std::vector<int> GenerateHost(model::Qwen2Model& model,const base::KVRequestSnapshot& snapshot,int seed,int64_t delta,int steps,const std::vector<int32_t>& prompt){base::RequestId id=-1;if(!model.kv_cache_manager()->restore_request_snapshot(snapshot,&id))throw std::runtime_error("restore failed");return GenerateRequest(model,id,seed,delta,steps,prompt);}
std::vector<int> GenerateExternal(model::Qwen2Model& model,const base::ExternalKVRequestState& state,int seed,int64_t delta,int steps,const std::vector<int32_t>& prompt){base::RequestId id=-1;if(!model.kv_cache_manager()->restore_external_request(state,&id))throw std::runtime_error("external page-table restore failed");return GenerateRequest(model,id,seed,delta,steps,prompt);}
std::vector<int> CancelExternal(model::Qwen2Model& model,const base::ExternalKVRequestState& state,int seed,int64_t delta,int steps_before_cancel,const std::vector<int32_t>& prompt){base::RequestId id=-1;if(!model.kv_cache_manager()->restore_external_request(state,&id))throw std::runtime_error("external page-table restore failed");serving::SchedulerConfig cfg;cfg.max_num_seqs=1;cfg.max_num_batched_tokens=16;serving::Scheduler scheduler(cfg,model.kv_cache_manager());serving::GenerationConfig generation(steps_before_cancel+2);generation.sampling.repetition_penalty=1.05;const int32_t initial_context=model.kv_cache_manager()->get_context_len(id);const int64_t client_id=scheduler.add_decode_ready_request(id,prompt,generation,initial_context,seed);size_t produced=1;auto allocator=base::CUDADeviceAllocatorFactory::get_instance();for(int step=0;step<steps_before_cancel&&scheduler.has_active_requests();++step){auto output=scheduler.schedule_step();if(output.total_tokens!=1)throw std::runtime_error("cancel decode was not admitted");auto batch=scheduler.build_decode_batch(output,model.device_context()->compute_queue);int32_t position=initial_context+delta+static_cast<int32_t>(produced)-1;allocator->memcpy(&position,batch.positions.ptr<int32_t>(),sizeof(position),base::MemcpyKind::kMemcpyCPU2CUDA,model.device_context()->compute_queue,false);auto status=model.forward_decode_batch(batch);if(!status)throw std::runtime_error(status.get_err_msg());auto sampled=model.batch_sample(batch,output);produced+=sampled.size();scheduler.process_outputs(output,batch,sampled,[](int32_t){return false;});}if(!scheduler.cancel_request(client_id,"cancelled_by_coordinator"))throw std::runtime_error("decode cancellation failed");auto finished=scheduler.pop_finished();if(finished.size()!=1||!finished[0].failed||finished[0].finish_reason!="cancelled_by_coordinator")throw std::runtime_error("cancelled decode did not reach terminal state");return finished[0].output_tokens;}
bool Synchronize(){return cudaDeviceSynchronize()==cudaSuccess;}

class IpcGrantGuard {
 public:
  explicit IpcGrantGuard(data::DataClient* client) : client_(client) {}
  ~IpcGrantGuard() {
    if (active_) client_->release_ipc_slots(token_);
  }
  void arm(const data::LeaseToken& token) { token_ = token; active_ = true; }
  void release() {
    if (active_) client_->release_ipc_slots(token_);
    active_ = false;
  }
  void retain_after_process_exit() { active_ = false; }

 private:
  data::DataClient* client_ = nullptr;
  data::LeaseToken token_;
  bool active_ = false;
};
}

int main(int argc,char** argv){
  google::InitGoogleLogging(argv[0]);if(argc<10){std::cerr<<"usage: pbe_multi_role_vlm prefill|decode|prefill-ipc|decode-ipc|decode-cancel-ipc MODEL TOKENIZER ENDPOINT DEVICE UNUSED ID_HEX KV_REP [STEPS]\n";return 2;}
  const std::string role=argv[1],model_file=argv[2],tokenizer=argv[3],endpoint=argv[4],id_hex=argv[7],kv_rep=argv[8];const int device=std::stoi(argv[5]);const bool external=role=="prefill-ipc"||role=="decode-ipc"||role=="decode-cancel-ipc";data::DataClient client(endpoint);data::ContentId id;if(!Hex(id_hex,&id.digest))return 2;
  data::RemoteDataLease kv_lease;base::ExternalKVRequestState external_state;data::LeaseToken prefix_pool_lease;int external_seed=0;int64_t external_delta=0;std::vector<int32_t> external_prompt;
  if(role=="decode-ipc"||role=="decode-cancel-ipc"){auto error=client.acquire(data::DataKind::kKVPage,id,data::RepresentationIdFromString(kv_rep),data::DataLeaseKind::kCompute,&kv_lease);if(error!=data::DataError::kOk||!UnpackExternal(kv_lease.bytes,&external_state,&prefix_pool_lease,&external_seed,&external_delta,&external_prompt))return 4;}
  model::Qwen2Model model(base::TokenizerType::kEncodeBpe,tokenizer,model_file,false);model.set_kv_cache_blocks_per_layer(256);model.set_serving_workspace_token_capacity(256);model.set_radix_cache_enabled(false);std::shared_ptr<data::CudaIpcPoolImport> ipc;data::IpcPoolDescriptor descriptor;
  data::IpcSlotGrant slot_grant;uint64_t replica_bytes=0;double replica_ms=0;std::string transport_path;
  IpcGrantGuard slot_guard(&client);
  if(external){if(client.get_ipc_pool(&descriptor)!=data::DataError::kOk||(role=="prefill-ipc"&&descriptor.device!=device))return 3;const uint32_t requested=role=="prefill-ipc"?std::max(16,descriptor.num_blocks/4):4;if(client.reserve_ipc_slots(requested,&slot_grant)!=data::DataError::kOk)return 3;slot_guard.arm(slot_grant.token);ipc=std::make_shared<data::CudaIpcPoolImport>();std::string error;std::vector<int32_t> initial;if(role=="decode-ipc"||role=="decode-cancel-ipc")initial=CommonBlocks(external_state);const std::vector<int32_t>& replica_slots=initial.empty()?slot_grant.slots:initial;if(!ipc->open(descriptor,device,&error)||!ipc->prepare_compute_view_slots(replica_slots,nullptr,&replica_bytes,&replica_ms,&transport_path,&error)){std::cerr<<error<<"\n";return 3;}model.set_external_kv_pool(Binding(descriptor,ipc,initial,slot_grant.slots));}
  auto status=model.init(base::DeviceType::kDeviceCUDA,device);if(!status)return 3;
  if(role=="prefill"||role=="prefill-ipc"){
    data::RemoteDataLease vision;auto error=client.acquire(data::DataKind::kTensorBundle,id,data::RepresentationIdFromString("pbe-qwen25-vl-vision-bf16-bundle-v2"),data::DataLeaseKind::kCompute,&vision);if(error==data::DataError::kNotReady||error==data::DataError::kUnknownObject)error=client.acquire(data::DataKind::kTensorBundle,id,data::RepresentationIdFromString("qwen25-vl-request-bundle-v3"),data::DataLeaseKind::kCompute,&vision);if(error!=data::DataError::kOk)return 4;data::TensorBundleSchema schema;std::string reason;if(data::DecodeTensorBundlePayload(vision.bytes.data(),vision.bytes.size(),&schema,&reason)!=data::DataError::kOk){std::cerr<<reason;return 5;}
    const auto* features=Find(schema,"image_features");const auto* ids=Find(schema,"input_ids");const auto* positions_component=Find(schema,"position_ids");const auto* delta_component=Find(schema,"rope_delta");std::vector<int32_t> tokens,positions;std::vector<int64_t> deltas;if(!features||features->shape.size()!=2||!ReadComponent(vision.bytes,ids,&tokens)||!ReadComponent(vision.bytes,positions_component,&positions)||!ReadComponent(vision.bytes,delta_component,&deltas)||deltas.size()!=1||positions.size()!=tokens.size()*3)return 6;
    auto embeddings=model.embedding(tokens);size_t image_begin=0;while(image_begin<tokens.size()&&tokens[image_begin]!=151655)++image_begin;if(image_begin+features->shape[0]>tokens.size()||features->shape[1]!=static_cast<uint64_t>(embeddings.input_embeddings.get_dim(1)))return 6;auto allocator=base::CUDADeviceAllocatorFactory::get_instance();allocator->memcpy(vision.bytes.data()+features->byte_offset,embeddings.input_embeddings.ptr<uint16_t>(image_begin*features->shape[1]),features->byte_length,base::MemcpyKind::kMemcpyCPU2CUDA,nullptr,true);tensor::Tensor mrope(base::DataType::kDataTypeInt32,3,tokens.size(),true,allocator);allocator->memcpy(positions.data(),mrope.ptr<int32_t>(),mrope.byte_size(),base::MemcpyKind::kMemcpyCPU2CUDA,nullptr,true);
    serving::SchedulerConfig cfg;cfg.max_num_seqs=1;cfg.max_num_batched_tokens=256;cfg.prefill_chunk_cap=256;serving::Scheduler scheduler(cfg,model.kv_cache_manager());scheduler.add_request(tokens,serving::GenerationConfig(1));auto scheduled=scheduler.schedule_step();auto batch=scheduler.build_mixed_batch(scheduled,model.device_context()->compute_queue);batch.input_embeddings_override=embeddings.input_embeddings;batch.mrope_positions=mrope;status=model.forward_mixed_batch(batch);if(!status)return 7;auto sampled=model.batch_sample(batch,scheduled);const int generation_seed=sampled[0];std::vector<uint8_t> payload;std::vector<int> oracle;
    const int oracle_steps=argc>9?std::stoi(argv[9]):16;
    if(external){base::ExternalKVRequestState state;if(!model.kv_cache_manager()->export_external_request(batch.request_ids[0],&state)||!Synchronize())return 8;if(oracle_steps>0){base::RequestId branch=-1;base::BranchTokenBoundaries boundaries{state.valid_tokens,0,0};if(!model.kv_cache_manager()->fork_request(batch.request_ids[0],boundaries,true,generation_seed,&branch))return 8;oracle=GenerateRequest(model,branch,generation_seed,deltas[0],oracle_steps,tokens);}payload=PackExternal(state,slot_grant.token,generation_seed,deltas[0],tokens);}else{base::KVRequestSnapshot snapshot;if(!model.kv_cache_manager()->snapshot_request(batch.request_ids[0],&snapshot))return 8;if(oracle_steps>0)oracle=GenerateHost(model,snapshot,generation_seed,deltas[0],oracle_steps,tokens);payload=PackHost(snapshot,generation_seed,deltas[0],tokens);}
    uint64_t owner=0;client.ping(&owner);data::DataReservation reservation;reservation.operation={owner,(uint64_t(getpid())<<32)^std::chrono::steady_clock::now().time_since_epoch().count()};reservation.kind=data::DataKind::kKVPage;reservation.content=data::ContentIdFromBytes(payload.data(),payload.size());reservation.representation=data::RepresentationIdFromString(kv_rep);reservation.logical_bytes=payload.size();data::AllocationHandle handle;error=client.reserve(reservation,&handle);if(error!=data::DataError::kOk)return 9;data::DataRef ref;error=client.seal(handle,payload,data::DataChecksum(payload.data(),payload.size()),&ref);client.release_producer(handle);client.release(vision.token);if(error==data::DataError::kOk&&external)slot_guard.retain_after_process_exit();std::cout<<"PBE_VLM_PREFILL pid="<<getpid()<<" vision_content="<<id_hex<<" kv_content="<<Hex(ref.content.digest)<<" prefill_tokens="<<tokens.size()<<" media_rows="<<features->shape[0]<<" metadata_bytes="<<payload.size()<<" rope_delta="<<deltas[0]<<" pool_owner="<<(external?descriptor.owner_incarnation:0)<<" pool_grant_service="<<(external?slot_grant.token.service_incarnation:0)<<" pool_grant_consumer="<<(external?slot_grant.token.consumer_incarnation:0)<<" pool_grant="<<(external?slot_grant.token.lease_id:0)<<" pool_slots="<<(external?slot_grant.slots.size():0)<<" transport="<<(external?"same_gpu_cuda_ipc":"host_snapshot")<<" oracle_tokens=";for(int token:oracle)std::cout<<token<<",";std::cout<<" text="<<model.decode(oracle)<<"\n";return error==data::DataError::kOk?0:10;
  }
  if(role=="decode"||role=="decode-ipc"||role=="decode-cancel-ipc"){
    std::vector<int> output;int seed=0;int64_t delta=0;std::vector<int32_t> prompt;size_t imported=0;
    const int steps=argc>9?std::stoi(argv[9]):16;if(external){seed=external_seed;delta=external_delta;prompt=external_prompt;output=role=="decode-cancel-ipc"?CancelExternal(model,external_state,seed,delta,steps,prompt):GenerateExternal(model,external_state,seed,delta,steps,prompt);if(!Synchronize())return 6;imported=kv_lease.bytes.size();client.release(kv_lease.token);slot_guard.release();}else{data::RemoteDataLease lease;auto error=client.acquire(data::DataKind::kKVPage,id,data::RepresentationIdFromString(kv_rep),data::DataLeaseKind::kCompute,&lease);if(error!=data::DataError::kOk)return 4;base::KVRequestSnapshot snapshot;if(!UnpackHost(lease.bytes,&snapshot,&seed,&delta,&prompt))return 5;output=GenerateHost(model,snapshot,seed,delta,steps,prompt);imported=lease.bytes.size();client.release(lease.token);}
    std::cout<<"PBE_VLM_DECODE pid="<<getpid()<<" device="<<device<<" cancelled="<<(role=="decode-cancel-ipc"?1:0)<<" imported_metadata_bytes="<<imported<<" prefill_tokens_saved="<<(external?external_state.valid_tokens:0)<<" rope_delta="<<delta<<" pool_owner="<<(external?descriptor.owner_incarnation:0)<<" prefix_grant="<<(external?prefix_pool_lease.lease_id:0)<<" private_grant="<<(external?slot_grant.token.lease_id:0)<<" private_slots="<<(external?slot_grant.slots.size():0)<<" cow_bytes="<<model.kv_cache_manager()->total_block_copy_bytes()<<" replica_bytes="<<replica_bytes<<" replica_ms="<<replica_ms<<" transport="<<(external?transport_path:"host_snapshot")<<" tokens=";for(int token:output)std::cout<<token<<",";std::cout<<" text="<<model.decode(output)<<"\n";return 0;
  }
  return 2;
}
