#include <chrono>
#include <cstring>
#include <iostream>
#include <string>
#include <unistd.h>
#include "base/base.h"
#include "data/data_client.h"
#include "data/kv_snapshot_codec.h"
#include "data/wire_io.h"
#include "model/qwen2.h"

namespace {
std::string Hex(const data::Digest256& d){static const char x[]="0123456789abcdef";std::string s;for(auto b:d){s.push_back(x[b>>4]);s.push_back(x[b&15]);}return s;}
bool FromHex(const std::string&s,data::Digest256*d){if(s.size()!=64)return false;auto cv=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;};for(size_t i=0;i<32;++i){int a=cv(s[2*i]),b=cv(s[2*i+1]);if(a<0||b<0)return false;(*d)[i]=(a<<4)|b;}return true;}
std::string Chat(const std::string& q){return "<|im_start|>system\nYou are a helpful assistant.\n<|im_end|>\n<|im_start|>user\n"+q+"\n<|im_end|>\n<|im_start|>assistant\n";}
bool FromHex(const std::string& s, data::ContentId* content) {
  return content != nullptr && FromHex(s, &content->digest);
}
std::vector<int32_t> Generate(model::Qwen2Model& model,const base::KVRequestSnapshot& snapshot,int32_t seed,int steps){base::RequestId id=-1;if(!model.kv_cache_manager()->restore_request_snapshot(snapshot,&id))throw std::runtime_error("restore snapshot failed");std::vector<int32_t> result;int32_t token=seed;auto pos=model.get_buffer(model::ModelBufferType::kInputPos);for(int i=0;i<steps&&!model.is_sentence_ending(token);++i){result.push_back(token);pos.index<int32_t>(0)=snapshot.valid_tokens+i;auto emb=model.embedding({token});auto input=model.fill_input(pos,emb,false);int32_t next=0;auto status=model.predict_with_request(input,pos,id,false,next);if(!status)throw std::runtime_error(status.get_err_msg());token=next;}model.kv_cache_manager()->free_request(id);return result;}
std::vector<uint8_t> Pack(const base::KVRequestSnapshot&s,int32_t seed){std::vector<uint8_t> encoded,out;data::EncodeKVSnapshot(s,&encoded);data::wire::Put<uint32_t>(0x54584250,&out);data::wire::Put<uint16_t>(1,&out);data::wire::Put<uint16_t>(0,&out);data::wire::Put<uint32_t>(seed,&out);data::wire::Put<uint64_t>(encoded.size(),&out);data::wire::PutBytes(encoded.data(),encoded.size(),&out);return out;}
bool Unpack(const std::vector<uint8_t>&b,base::KVRequestSnapshot*s,int32_t*seed){const uint8_t*p=b.data(),*e=p+b.size();uint32_t magic=0,raw=0;uint16_t v=0,r=0;uint64_t n=0;if(!data::wire::Get(&p,e,&magic)||!data::wire::Get(&p,e,&v)||!data::wire::Get(&p,e,&r)||!data::wire::Get(&p,e,&raw)||!data::wire::Get(&p,e,&n)||magic!=0x54584250||v!=1||r||n!=static_cast<uint64_t>(e-p))return false;*seed=static_cast<int32_t>(raw);return data::DecodeKVSnapshot(p,n,1ULL<<30,s)==data::DataError::kOk;}
}
int main(int argc,char**argv){google::InitGoogleLogging(argv[0]);if(argc<8){std::cerr<<"usage: pbe_multi_role_text prefill MODEL TOKENIZER ENDPOINT REP DEVICE PROMPT | decode MODEL TOKENIZER ENDPOINT REP DEVICE CONTENT [STEPS]\n";return 2;}std::string role=argv[1],model_path=argv[2],tokenizer=argv[3],endpoint=argv[4],rep_name=argv[5];int device=std::stoi(argv[6]);model::Qwen2Model model(base::TokenizerType::kEncodeBpe,tokenizer,model_path,false);model.set_kv_cache_blocks_per_layer(128);model.set_serving_workspace_token_capacity(512);model.set_radix_cache_enabled(false);auto init=model.init(base::DeviceType::kDeviceCUDA,device);if(!init){std::cerr<<init.get_err_msg()<<"\n";return 3;}data::DataClient client(endpoint);auto representation=data::RepresentationIdFromString(rep_name);
  if(role=="prefill"){std::string prompt=Chat(argv[7]);auto tokens=model.encode(prompt);for(int i=0;tokens.size()%16!=0&&i<256;++i){prompt.insert(prompt.size()-1," ");tokens=model.encode(prompt);}if(tokens.empty()||tokens.size()%16!=0){std::cerr<<"could not align prompt to full page\n";return 4;}auto id=model.kv_cache_manager()->register_request();int32_t next=model.prefill_chunk(id,tokens,0,tokens.size());base::KVRequestSnapshot snapshot;if(!model.kv_cache_manager()->snapshot_request(id,&snapshot)){std::cerr<<"snapshot failed\n";return 5;}auto oracle=Generate(model,snapshot,next,16);auto payload=Pack(snapshot,next);uint64_t owner=0;auto status=client.ping(&owner);if(status!=data::DataError::kOk)return 6;data::DataReservation r;r.operation={owner,(static_cast<uint64_t>(getpid())<<32)^std::chrono::steady_clock::now().time_since_epoch().count()};r.kind=data::DataKind::kKVPage;r.content=data::ContentIdFromBytes(payload.data(),payload.size());r.representation=representation;r.logical_bytes=payload.size();data::AllocationHandle h;status=client.reserve(r,&h);if(status!=data::DataError::kOk)return 7;data::DataRef ref;status=client.seal(h,payload,data::DataChecksum(payload.data(),payload.size()),&ref);if(status!=data::DataError::kOk)return 8;client.release_producer(h);std::cout<<"PBE_TEXT_PREFILL pid="<<getpid()<<" device="<<device<<" content="<<Hex(ref.content.digest)<<" prefill_tokens="<<tokens.size()<<" kv_bytes="<<payload.size()<<" full_pages="<<tokens.size()/16<<" oracle_tokens=";for(auto x:oracle)std::cout<<x<<",";std::cout<<" oracle_text="<<model.decode(oracle)<<"\n";return 0;}
  if(role=="decode"){data::ContentId content;if(!FromHex(argv[7],&content))return 2;data::RemoteDataLease lease;auto status=client.acquire(data::DataKind::kKVPage,content,representation,data::DataLeaseKind::kCompute,&lease);if(status!=data::DataError::kOk){std::cerr<<"acquire error="<<static_cast<int>(status)<<"\n";return 7;}base::KVRequestSnapshot snapshot;int32_t seed=0;if(!Unpack(lease.bytes,&snapshot,&seed))return 8;auto generated=Generate(model,snapshot,seed,argc>8?std::stoi(argv[8]):16);status=client.release(lease.token);if(status!=data::DataError::kOk)return 9;std::cout<<"PBE_TEXT_DECODE pid="<<getpid()<<" device="<<device<<" lease="<<lease.token.lease_id<<" imported_bytes="<<lease.bytes.size()<<" prefill_tokens_saved="<<snapshot.valid_tokens<<" tokens=";for(auto x:generated)std::cout<<x<<",";std::cout<<" text="<<model.decode(generated)<<"\n";return 0;}return 2;}
